# Generated by Django 4.1.2 on 2022-11-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_account', '0004_tweet_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='type',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
